.gitignore, leap_c/mpc.py, leap_c/util.py
Added the cleanup of acados files that were created into temporary folders by the AcadosFileManager.
For now adding the build and generate options is not possible, as the AcadosOcpBatchSolver does not allow those options. The possibility could be added for a later point, if the AcadosOcpBatchSolver would be updated!
A future feature would be to reduce the number of solvers created in the MPC class to only the BatchSolver.
=> AcadosFileManager configured for temp directories

leap_c/mpc.py, tests/leap_c/test_mpc.py
Previously, it was possible to give an u0 in the mpc_input that is outside of lbu and ubu as defined in the ocp without anything complaining. If not desired (which is most likely), this is a potentially sneaky bug. This PR is for catching this bug. If not raising an exception in this case is desired, it can easily be turned off by using a new flag.
=> Fix potential u0 bug

leap_c/collate.py, leap_c/rl/replay_buffer.py, leap_c/rl/sac.py, leap_c/rl/trainer.py, leap_c/scripts/rl/linear_system_sac.py, leap_c/scripts/rl/pendulum_on_cart_sac.py, tests/leap_c/test_replay_buffer.py
Summary:
- Made ReplayBuffer work for more general data (not only transition tuples of shape s, a, r, s', d like previously).
- Added collating of Acados Iterates.
- Added recursive .to to move nested tensors to the correct device (and convert it to the "correct" type). In particular, this
assumes that people want all tensors to be of the same type given in the initialization. I am not sure if we want to 
leave it like this for now or what a good standard would be 
(but also the function can be easily overwritten to take special cases into account if someone would wish for it).
- Now the ReplayBuffer may return tensors of shape (batch_size, ) again instead of (batch_size, 1) (e.g., the reward or the done 
tensors are such cases). The relevant code where this has caused a problem (SAC …
=> Extend replay buffer

.github/workflows/tests.yml, leap_c/mpc.py, leap_c/utils.py
- Requires less options for sensitivity solver
- Faster, as only one factorization is done in the sensitivity solver
- updated acados submodule
See https://github.com/acados/acados/pull/1432
=> Use new `setup_qp_matrices_and_factorize()` function from acados for sensitivity solver

leap_c/rl/sac.py, leap_c/rl/sac_fop.py, leap_c/rl/sac_zop.py
The target calculation has been messed up in #21 (wrong shapes), this fixes it again (also fixes another bug that only appears when trying to use prepare_mpc_state in sac_fop's MpcSacActor).
=> Bugfix target calculation

leap_c/linear_mpc.py, leap_c/mpc.py, leap_c/rl/sac_fop.py, leap_c/rl/sac_zop.py, leap_c/task.py, leap_c/trainer.py, tests/leap_c/test_mpc.py
This PR tackles #23 , we simplified the code:
1. We always pass a None if we want to rely on the `init_state_fn`, simplifying the code. This is also similar how an initial state is provided in LSTMS in PyTorch. If a user is interested in getting the initial state where we passed None, the initial_state_fn can still be called. 
2. We further have now an explicit initial_state_fn that puts zeroes everywhere. This allows users to understand what such a function could look like! Even though we now set the Acados solver state two times to zero....
3. We deleted some deprecated MPC class code!
=> Initial state handling

leap_c/rl/sac_fop.py
Logging masked samples contained a bug, because the status has been removed from pi_o before via pi_o.select(mask_status).
=> Fix logging masked samples

.github/workflows/tests.yml, leap_c/examples/pendulum_on_a_cart/mpc.py, leap_c/mpc.py, tests/leap_c/conftest.py, tests/leap_c/test_autograd.py, tests/leap_c/test_mpc.py, tests/leap_c/test_pendulum_on_cart.py
- Added support for parametric `LINEAR_LS` and `NONLINEAR_LS` cost with `p_global values` (translated to EXTERNAL)
- Unified cost update interface for both forward and sensitivity solvers
- Removed special treatment requirements in `MpcParameter`
- Enabled Gauss-Newton Hessian approximations in forward solver with exact Hessians in sensitivity solver. Using the same interface to update cost parameters
- Avoid expensive calls to `cost_set`
- Refactored cost functions and sensitivity options in core `MPC` class
- Modified pendulum on cart MPC example to utilize `NONLINEAR_LS` cost type
- Renamed and removed obsolete parameters
- Updated test fixtures and test functions for compatibility
This enhancement provides a more elegant and consistent approach to cost handling. By translating …
=> Gauss-Newton with external cost

leap_c/trainer.py
Make whole functionality of wandb init accessible without introducing a new field in the config for every kwarg. 
Instead now one field in the config `wandb_init_kwargs` can be specified, which will be passed to wandb.init().
=> Convenient access to wandb.init() kwargs

.github/workflows/tests.yml, leap_c/examples/chain/mpc.py, leap_c/examples/pendulum_on_a_cart/mpc.py, leap_c/examples/pointmass/mpc.py, leap_c/examples/quadrotor/mpc.py, leap_c/mpc.py, leap_c/rl/sac_fop.py, leap_c/run.py, leap_c/utils.py
The number of threads to use for parallelizing the mpc batch calculations previously had to be set in the ocp formulation. 
It can now be set dynamically at any point in time, which is exposed in the Mpc class by the property `num_threads_in_batch_methods` and the equally named constructor argument.
Further, it was actually not set at all by default, despite large computational speedups being enabled by it.
Hence, there is now a new field `num_threads_in_mpc_batch_methods` in the SacFopAlgorithmConfig (SacFop is currently the only architecture using mpc batch calculations).
It is set to  `4` threads by default.
Enabled by: [acados/acados/#1483](https://github.com/acados/acados/pull/1483)
=> Make Parallelization more accessible

leap_c/examples/pendulum_on_a_cart/env.py
Previously the initial state in the cartpole balancing started at 0, now the starting position is chosen randomly (Customizable via reset options).
=> Make cartpole balancing start randomly

leap_c/nn/extractor.py, leap_c/nn/utils.py, leap_c/task.py, tests/leap_c/test_nn_utils.py, tests/leap_c/test_resurrect.py
Added min-max-scaling into the extractor such that observations are now normalized. This can be useful for a lot of different  environments:
- Renamed IdentityExtractor to MinMaxScalingExtractor.
- Added a check to the min-max-scaling to ensure that there are correctly set min-max-bounds
=> Add MinMaxScalingExtractor

leap_c/collate.py, leap_c/examples/chain/mpc.py, leap_c/examples/pendulum_on_a_cart/mpc.py, leap_c/mpc.py, leap_c/nn/extractor.py, leap_c/nn/modules.py, leap_c/task.py, leap_c/trainer.py
- Use perf_counter to measure the time the whole batch solve takes and add it to the solver stats.
- set `qp_tol=1e-7` for the chain and the cartpole mpc, getting rid of a certain type of non-convergence (see comment below).
- update a docstring
- Fix bug in wandb logging
- Fix important bug concerning sensitivities
- Fix small bug in batch collate of batchiterates
- Change default Extractor in Task back to IdentityExtractor for now, because min max scaling can make problems with some observation spaces (see cartpole)
=> General improvements

leap_c/examples/pendulum_on_a_cart/task.py
Avoid confusion in the future by creating a new task for cartpole swingup with the longer horizon
=> long horizon swingup task

leap_c/examples/pendulum_on_a_cart/task.py
This fixes the Cart Pole task with long horizon accidentally inheriting from Task instead of from the other swingup task (and hence, crashing due to abstract methods).
=> Fix inheritance in Cart Pole

leap_c/utils/torch_autograd.py, tests/leap_c/utils/test_torch_autograd.py
This PR prepares the acados module refactor by providing a generic way to create PyTorch autograd Functions.
**Motivation:** Decoupling the creation of autograd functionalities for PyTorch from the acados sensitivity calculations, allows wrapping the differentiable capabilities also for Jax at a later point.
**Benefits**:
- Improving our current implementation of the PyTorch layer for acados, by being more general.
- We introduce a new `custom_ctx` object for layers that can be wrapped. This results in an explicit handling of the information shared between the forward and backward pass in leap_c. In some cases, we want to do more than just forward and backward passes but also calculate specific sensitivities. The ctx object outside of PyTorch allows then to store the information even …
=> Add torch autograd functionality.

leap_c/ocp/acados/data.py, leap_c/ocp/acados/diff_mpc.py, leap_c/ocp/acados/initializer.py, leap_c/ocp/acados/layer.py, leap_c/ocp/acados/mpc.py, leap_c/ocp/acados/torch.py, leap_c/ocp/acados/utils/prepare_solver.py, leap_c/ocp/acados/utils/solve.py, tests/leap_c/ocp/acados/conftest.py, tests/leap_c/ocp/acados/test_acados_torch.py
This PR renames some classes to make it more consistent with the branding of differentiable MPC:
- `AcadosImplicitLayer` is renamed to `AcadosDiffMpc`.
- `AcadosImplicitFunction` is renamed to `AcadosDiffMpcFunction`.
- `AcadosInitializer` is renamed to `AcadosDiffMpcInitializer`.
- `SensitivityField` is renamed to `AcadosDiffMpcSensitivityOptions`
The docstrings and tests are updated accordingly. Furthermore, we did the following small improvements:
- Fixed `tests/leap_c/ocp/acados/test_acados_torch.py::test_file_management` on MacOs and removed some unnecessary fixtures.
- Added deprecation warnings to the old `Mpc` class.
=> Rename to AcadosDiffMpc

leap_c/examples/cartpole/config.py, leap_c/examples/cartpole/controller.py, leap_c/ocp/acados/parameters.py, tests/leap_c/examples/test_controllers.py, tests/leap_c/ocp/acados/conftest.py, tests/leap_c/ocp/acados/test_acados_torch.py, tests/leap_c/ocp/acados/test_param_manager.py
This pull request introduces the new `AcadosParamManager` class along with minor improvements and additions to the test suite for `AcadosImplicitLayer` and parameter management functionality.
- **Parameter Class**: Introduced high-level `Parameter` class with configurable properties:
- `name`, `value`, `lower_bound`, `upper_bound`
- `differentiable` and `varying` flags for flexible parameter configuration
- `fix` flag to indicate a fix value (not a settable parameter)
- Allows users to define parameter sets without requiring knowledge of internal CasADi tools or acados interface details
- **AcadosParamManager Class**: New parameter management system that:
- Handles symbolic and numerical variables collected via `Parameter` objects
- Manages mapping between symbolic variables and dense …
=> Stagewise varying differentiable params

leap_c/trainer.py, leap_c/utils/logger.py
This PR proposes the following changes:
1. fix accessing `wandb_init_kwargs`, e.g., when setting custom run names
2. add an initial policy validation (perhaps the initial validation score does not start at zero)
3. move closing of the Logger before the `return` command, otherwise it does not close after the run in some cases
Also, I noticed that when `val_report_score` is `"final"`, the best score is returned instead of the last one.
Should a `"best"` option be added and the rest modified accordingly?
=> Logging: minor fixes

leap_c/examples/chain/env.py, leap_c/trainer.py
I would suggest to slightly update the return value of `Trainer.run()`.
Also, there was a warning with the chain example related to [this thread](https://stackoverflow.com/questions/60149105/userwarning-warn-box-bound-precision-lowered-by-casting-to-float32).
=> Trainer: return value of `run`

leap_c/torch/nn/mlp.py, leap_c/torch/rl/sac.py, leap_c/torch/rl/sac_fop.py, leap_c/torch/rl/sac_zop.py, tests/leap_c/torch/nn/test_mlp.py
Provides a simple way to replace the `Mlp` block with a constant parameter. Setting `hidden_dims` of the `MlpCfg` to either `None` or an empty sequence will replace the MLP with a constant parameter.
=> Const param mlp

.gitmodules
The current URL requires users to set git authentication to GitHub via SSH. If that is not the case, when running the command ``git submodule update --init``, the following error (or similar) will pop up
```bash
git@github.com: Permission denied (publickey). fatal: Could not read from remote repository.
```
By using HTTPS instead, anybody should be able to clone the `leap-c` repository and update its submodule smoothly, with no SSH setup required.
=> Acados submodule's url as HTTPS rather than SSH

leap_c/ocp/acados/parameters.py, tests/leap_c/ocp/acados/conftest.py
This PR removes (probably unintentional) class attributes from `AcadosParameter` and `AcadosParameterManager`. 
Class attributes are attributes defined at the class level and assigned a default value. These attributes are then **shared across all instances** of that class. From the code, this does not seem to the intended purpose, e.g., each `AcadosParameterManager` instance should have its own `parameters` dict.
I also turned `AcadosParameter` to a dataclass so as to allow `vary_stages` to have a default empty list value. In the current implementation, the default value is mutable, thus shared across all instances, as aforementioned. 
I also removed `None` as a possible value from `learnable_parameters` and similar fields in `AcadosParameterManager`. It seems these fields are always …
=> Removed class attributes in leap_c/ocp/acados/parameters.py

leap_c/ocp/acados/diff_mpc.py, leap_c/ocp/acados/torch.py
Changing `N_BATCH_MAX` and `NUM_THREADS_BATCH_SOLVER` to different values (e.g., in my case to higher values for Monte Carlo computations) is not straightforward. Before importing any other leap-c module, one must
```python
import leap_c.ocp.acados.diff_mpc as leap_c_diff_mpc
leap_c_diff_mpc.N_BATCH_MAX = ...
leap_c_diff_mpc.NUM_THREADS_BATCH_SOLVER = ...
from leap_c import ...  # other leap-c imports
```
so that the new values for these two constants are actually used.
By instead exposing two new arguments in `AcadosDiffMpc.__init__` we could have them passed as arguments when creating the controller.
=> exposing `n_batch_max` and `num_threads_batch_solver` in `AcadosDiffMpc.__init__`

pyproject.toml
Now that `wandb` is no longer a required dependency (which would have installed `PyYAML` automatically), we have to explicitly add `PyYAML` as a new dependency. It is used in `leap_c/trainer.py` to dump configurations as yaml files.
=> Missing dependency on PyYAML after removal of wand from dependencies

leap_c/examples/cartpole/acados_ocp.py, leap_c/examples/chain/acados_ocp.py, leap_c/examples/hvac/config.py, leap_c/examples/pointmass/acados_ocp.py, leap_c/ocp/acados/parameters.py, tests/leap_c/ocp/acados/conftest.py, tests/leap_c/ocp/acados/test_acados_parameters.py
This PR refactors the `AcadosParameter` and `AcadosParameterManager` classes with the following changes:
**Key Changes:**
- Renames `vary_stages` parameter to `end_stages` for clearer semantics
- Enforces validation: when `end_stages` is provided, the last entry must be either `N_horizon` (terminal stage) or `N_horizon - 1`
- Enables users to specify parameters that don't exist at the terminal stage
- Facilitates implementation of additional use cases, such as parameters that vary at every stage
⚠️ **Breaking Change:**
The entries in `end_stages` now define the **last element** of an interval where the parameter should be set. This differs from the previous `vary_stages` implementation, which defined the **first stage** where the parameter had a different symbol.
**Migration:** Update any …
=> Parameter manager fix vary stages convention

leap_c/trainer.py, scripts/run_controller.py
Previous PR #127 inadvertently introduced a bug by renaming `cfg.val_freq` to the older `cfg.val_interval` in `Trainer.run()`. 
This PR fixes the bug, and removes also another usage of the old `val_interval` that I found still lingering in the code base.
More noteworthy, no test picked this bug up. So no test is running `Trainer.run()` as of now, likely
=> Fix bug from previous PR #127

leap_c/torch/rl/sac.py, leap_c/torch/rl/sac_fop.py, leap_c/torch/rl/sac_zop.py, leap_c/torch/utils/seed.py, leap_c/trainer.py, leap_c/utils/gym.py, leap_c/utils/rollout.py
This PR attempts to enforce reproducibility during validation and training. 
Essentially, the proposed approach consists in 1) creating a `np.random.Genrator` with the specified run seed and assigning it to the trainer, and 2) using said `np.random.Genrator` to generate a (hopefully, kinda unique) seed every time `env.reset` is called.
=> Improving reproducibility

leap_c/controller.py, leap_c/examples/cartpole/controller.py, leap_c/examples/chain/controller.py, leap_c/examples/pointmass/controller.py, leap_c/ocp/acados/controller.py, leap_c/ocp/acados/torch.py
Previously, people could instantiate the AcadosController already (without it working), 
because it would just inherit the init of nn.Module. 
This PR changes the AcadosController such that it provides an init method, and changes the examples accordingly.
Also small fixes to typehints and documentation.
=> Improve AcadosController

docs/source/index.md
Forgot to change the index, so the troubleshooting tab was not shown
=> Fix webpage
